const cartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  ADD_FROM_LOCAL_STORAGE: "ADD_FROM_LOCAL_STORAGE",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
  DECREASE_QUANTITY: "DECREASE_QUANTITY",
  INCREASE_QUANTITY: "INCREASE_QUANTITY",
};

export default cartTypes;
