const cartTypes = {
  ADD_TO_CART: "ADD_TO_CART",
  REMOVE_FROM_CART: "REMOVE_FROM_CART",
  REMOVE_ALL_FROM_CART: "REMOVE_ALL_FROM_CART",
  SET_CART_PRODUCTS: "SET_CART_PRODUCTS",
};

export default cartTypes;
