const categoryTypes = {
  SET_CATEGORIES: "SET_CATEGORIES",
  SET_CATEGORIES_ANCESTORS: "SET_CATEGORIES_ANCESTORS",
  SET_FILTER_CATEGORIES: "SET_FILTER_CATEGORIES",
};

export default categoryTypes;
