const modelsTypes = {
  SET_MODELS: "SET_MODELS",
  SET_UPLOADED_MODELS: "SET_UPLOADED_MODELS",
  UPLOAD_MODELS: "UPLOAD_MODELS",
  SET_PRODUCT_ID: "SET_PRODUCT_ID",
  RESET_MODELS: "RESET_MODELS",
  SET_MODELS_ERRORS: "SET_MODELS_ERRORS",
};

export default modelsTypes;
