const productTypes = {
  UPLOAD_PRODUCT: "UPLOAD_PRODUCT",
  ADD_PRODUCT: "ADD_PRODUCT",
  RESET_PRODUCTS: "RESET_PRODUCTS",
  SET_PRODUCT_ERRORS: "SET_PRODUCT_ERRORS",
  FETCH_PRODUCTS: "FETCH_PRODUCTS",
  FETCH_PRODUCT: "FETCH_PRODUCT",
  SET_PRODUCT_IMAGES: "SET_PRODUCT_IMAGES",
  SET_MODEL: "SET_MODEL",
  SET_SIMILAR_PRODUCTS: "SET_SIMILAR_PRODUCTS",
  SET_THUMBNAILS: "SET_THUMBNAILS",
  DELETE_PRODUCT: "DELETE_PRODUCT",
  EDIT_PRODUCT: "EDIT_PRODUCT",
  UPDATE_PRODUCT: "UPDATE_PRODUCT",
  SET_UPDATED_PRODUCT: "SET_UPDATED_PRODUCT",
};

export default productTypes;
