const imagesTypes = {
  SET_IMAGES: "SET_IMAGES",
  SET_UPLOADED_IMAGES: "SET_UPLOADED_IMAGES",
  UPLOAD_IMAGES: "UPLOAD_IMAGES",
  SET_PRODUCT_ID: "SET_PRODUCT_ID",
  SET_PRODUCT_ID_UPDATE: "SET_PRODUCT_ID_UPDATE",
  RESET_IMAGES: "RESET_IMAGES",
  SET_IMAGES_ERRORS: "SET_IMAGES_ERRORS",
  SET_THUMBNAILS: "SET_THUMBNAILS",
};

export default imagesTypes;
